FROM golang:1.20

WORKDIR /go/src/campus-fora-backend

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

EXPOSE 8080

ENV GO111MODULE=on
ENV PATH="${PATH}:/go/bin"
RUN ["go", "install", "github.com/githubnemo/CompileDaemon"]

ENTRYPOINT CompileDaemon -log-prefix=false -build="go build -o server ./cmd" -command="./server"
# RUN go build -o server ./cmd
# cmd ["./server]